# Based on the issue template
name: Feature request
description: Suggest an idea for this project
title: "[FEAT] <title>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
# This image is deprecated. We will not offer support for this image and it will not be updated.

Please migrate to our Kometa image instead:
https://github.com/linuxserver/docker-kometa

