#!/usr/bin/with-contenv bash

# halt startup if no config file is found
if [ ! -e "${PMM_CONFIG:-/config/config.yml}" ]; then
    echo "No config file found at ${PMM_CONFIG:-/config/config.yml}, halting init."
    sleep infinity
fi

cd / || exit 1

exec \
    s6-setuidgid abc python3 /app/pmm/plex_meta_manager.py --config "${PMM_CONFIG:-/config/config.yml}" --time "${PMM_TIME:-03:00}"
