#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
    /config

if [[ $PMM_RUN = "True" ]]; then
    touch /etc/services.d/plex-meta-manager/down
else
    echo "#!/usr/bin/with-contenv bash" > /etc/cont-init.d/55-oneshot
fi
